### ISSUE TITLE
get_histrory returns empty

### ISSUE THREAD

**Issue by srbharadwaj** [swapniljariwala/nsepy#116]
DATE: 10-FEB-2020
Installed the pkg today via pip

nifty_next50 = get_history(symbol="NIFTY NEXT 50",
                            start=date(2020,1,1),
                            end=date(2020,1,10),
                            index=True)

print(nifty_next50)
getting empty cell

Empty DataFrame
Columns: [Open, High, Low, Close, Volume, Turnover]
Index: []

**Comment by swapniljariwala** [comment]
I've updated the package. Please try pip install nsepy --upgrade

As of now it is working.

**Comment by sachinlionel** [comment]
still same, with version 0.8.

get_history is returning empty df.

On debugging i found this.  
looks like this link is not working  http://www1.nseindia.com/products/dynaContent/common/productsSymbolMapping.jsp

**Comment by devwrat55** [comment]
> I've updated the package. Please try pip install nsepy --upgrade
> 
> As of now it is working.

it is not working... can you please provide working program... i updated nsepy... i actually want deliverable historic data which is not available anywhere... please help... my mail id - devwratneve@gmail.com

**Comment by srbharadwaj** [comment]
As of today with 0.8 its working so closing the issue. Thanks
