### ISSUE TITLE
nsepy not working on Google Colab

### ISSUE THREAD

**Issue by ravis2k6** [swapniljariwala/nsepy#117]
Trying to install the updated version using
!pip install git+https://github.com/swapniljariwala/nsepy/tree/314c3da264caa4adc5baaf4ed3575d502ffcfcd4

I get the below response

Collecting git+https://github.com/swapniljariwala/nsepy/tree/314c3da264caa4adc5baaf4ed3575d502ffcfcd4
  Cloning https://github.com/swapniljariwala/nsepy/tree/314c3da264caa4adc5baaf4ed3575d502ffcfcd4 to /tmp/pip-req-build-xmf0dsih
  Running command git clone -q https://github.com/swapniljariwala/nsepy/tree/314c3da264caa4adc5baaf4ed3575d502ffcfcd4 /tmp/pip-req-build-xmf0dsih
  fatal: repository 'https://github.com/swapniljariwala/nsepy/tree/314c3da264caa4adc5baaf4ed3575d502ffcfcd4/' not found
ERROR: Command errored out with exit status 128: git clone -q https://github.com/swapniljariwala/nsepy/tree/314c3da264caa4adc5baaf4ed3575d502ffcfcd4 /tmp/pip-req-build-xmf0dsih Check the logs for full command output.

**Comment by swapniljariwala** [comment]
!pip install nsepy installs the nsepy but it seems google's ip is blocked by NSE so even that would not help.

**Comment by seedlit** [comment]
@swapniljariwala Does it mean that we will not be able to run it on GCP (Google Cloud Platform) as well? 
Has anyone tried running it on cloud?
