### ISSUE TITLE
nsepy is not working

### ISSUE THREAD

**Issue by lakhan47** [swapniljariwala/nsepy#118]
I tried to use it in local and also in google colab.
i installed the latest version of it, using 
`pip install nsepy`
there is no problem with installation but when i tried to execute commands it takes forever to run but no output. so i had to stop it.
I tried to run simple,
`data = get_history(symbol="SBIN", start=date(2020,1,1), end=date(2020,1,31))
data[['Close']].plot()`

Does anyone have any problem in fetching data ?
My whole code is
`from nsepy import get_history`
`from datetime import date`
`data = get_history(symbol="SBIN", start=date(2020,1,1), end=date(2020,1,31))`
`data[['Close']].plot()`

**Comment by akilv** [comment]
I am facing the same problem.

**Comment by akilv** [comment]
> I tried to use it in local and also in google colab.
> i installed the latest version of it, using
> `pip install nsepy`
> there is no problem with installation but when i tried to execute commands it takes forever to run but no output. so i had to stop it.
> I tried to run simple,
> `data = get_history(symbol="SBIN", start=date(2020,1,1), end=date(2020,1,31)) data[['Close']].plot()`
> 
> Does anyone have any problem in fetching data ?
> My whole code is
> `from nsepy import get_history`
> `from datetime import date`
> `data = get_history(symbol="SBIN", start=date(2020,1,1), end=date(2020,1,31))`
> `data[['Close']].plot()`

I fixed the issue by following the steps outlined under the thread - https://github.com/swapniljariwala/nsepy/issues/113

I would suggest to delete the current version of nsepy and follow the below steps as highlighted by Subinoy and it should do the trick. 

Hello Everyone,

Here I attached few screenshots which will help you to solve the issue with
nsepy installation.

1. You need to find this mail and link to the branch of the repo.

[image: Fix_repo.png]

2. When you will reach to the nsepy github by clicking only the above link
( this way it's easier to find) then click view files.
Look at the below pic. Don't download the Master branch. Look at the tree
of the branch start with 314.
[image: Fixed_repo.png]
3. Clone or download this branch of repo and cd to the nsepy-314 folder.

4. Issue the command python setup.py install

It should solve the problem with nsepy.

[image: Screen Shot 2020-01-14 at 11.52.41 AM.png]

Thanks
Subinoy

**Comment by swapniljariwala** [comment]
There is a problem with google ips probably, even 
```!wget https://www1.nseindia.com/``` is not working on these platforms
