### ISSUE TITLE
NSE Data is getting blocked in digital ocean server but works fine in local host

### ISSUE THREAD

**Issue by suhealpasha** [swapniljariwala/nsepy#119]
Hi @swapniljariwala  I am trying to fetch the nse data I tried

from nsetools import Nse
nse = Nse()
allStocksCode = nse.get_stock_codes()
print(allStockCode) ---> Works fine 
data = nse.get_quote('TCS') 
print(data) ----> Not working 

The above code works fine in local host but no response when I hosted in digital ocean server?

**Comment by dushmis** [comment]
I believe both nsepy & nsetools are different libraries 
https://github.com/vsjha18/nsetools
