### ISSUE TITLE
Period of data should be included in get_history function

### ISSUE THREAD

**Issue by Ashutosh-Badave** [swapniljariwala/nsepy#128]
Hi Swapnil,

nsepy is helpful but I wanted to check the data month wise and I had to do the maths to combine the data monthwise in python, which is really tiresome so thought if you can add argument of period so user can include daily or monthly or yearly in it.
 
Below link used for USA market, might be useful:
https://towardsdatascience.com/how-to-get-stock-data-using-python-c0de1df17e75

**Comment by swapniljariwala** [comment]
Thanks for the suggestion @Ashutosh-Badave , as of now its not in the roadmap
