### ISSUE TITLE
ssl-warnings

### ISSUE THREAD

**Issue by pannet1** [swapniljariwala/nsepy#14]
`$ python nsepy_example.py `

/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning

**Comment by swapniljariwala** [comment]
As mentioned in the url this happens because we (including me) are using Python versions older than 2.7.9, so we need to either upgrade pyOpenSSL or install latest python.
So as per this [link](https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2), I just now ran `pip install urllib3[secure]` on python 2.7.6, and I didn't get the warning after that.

Let me know if that solves the issue. (Installing urllib3 might need gcc and build tools)

**Comment by pannet1** [comment]
> i am afraid the problem is beyond rectification.

`sudo pip install urllib3[secure]`

The directory '/home/elementary/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/elementary/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: urllib3[secure] in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: idna>=2.0.0; python_version <= "2.7" and extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure])
Collecting pyOpenSSL>=0.14; python_version <= "2.7" and extra == "secure" (from urllib3[secure])
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6b53ff2310>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pyopenssl/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6b53ff2490>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pyopenssl/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6b53ff2610>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pyopenssl/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6b53ff2790>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pyopenssl/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6b53ff2910>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pyopenssl/
  Could not find a version that satisfies the requirement pyOpenSSL>=0.14; python_version <= "2.7" and extra == "secure" (from urllib3[secure]) (from versions: )
No matching distribution found for pyOpenSSL>=0.14; python_version <= "2.7" and extra == "secure" (from urllib3[secure])

> so i tried the pythonssl package that comes with my distribution (linux elementary)

`sudo apt-get install python-openssl`

Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-openssl is already the newest version.
python-openssl set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by swapniljariwala** [comment]
Somewhere in erros posted by you-
Requirement already satisfied: urllib3[secure] in /usr/local/lib/python2.7/dist-packages 

are you still getting warnings? I tried it in virtual environment as i don't want to mess with default python installation but it should work with default as well.
Try `pip3 install nsepy` and run `python3 nsepy_example.py` , good reason for you to try python3 😉

**Comment by pannet1** [comment]
> yes, unfortunately still getting errors. tried python3 too

`python3 nsepy_example.py`

Traceback (most recent call last):
  File "nsepy_example.py", line 1, in <module>
    from nsepy import get_history, get_index_pe_history
ImportError: No module named 'nsepy'

`pip3 install nsepy`

The program 'pip3' is currently not installed. You can install it by typing:

`sudo apt-get install python3-pip`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-pip : Depends: python3-setuptools but it is not going to be installed
               Depends: python3-requests but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

> this is not nsepy bug. so i thought its a good idea to mail you separately and was googling. now i now how you look even started following you in linked in. but unable to find your email id. can you make your email id public the one that is less trivial. :-)
