### ISSUE TITLE
getting wrong historical data 

### ISSUE THREAD

**Issue by bommojuvishu** [swapniljariwala/nsepy#141]
I got the wrong  historical data when I try to pull the infosys share data for past 5 years 
as you can see from the screen the infosys close price on 2016 -1-1 is  1105 .

![Capture](https://user-images.githubusercontent.com/34394466/81462832-e4711f80-91d2-11ea-9cb6-d53198d844fa.PNG)

but  in reality it never crossed 700 mark in 2016. Please fix bug
![Capture 2](https://user-images.githubusercontent.com/34394466/81462910-619c9480-91d3-11ea-8fa8-a1e9beb88516.PNG)

**Comment by wnds** [comment]
The same data is available on NSE website as well so this is not an issue with numpy rather it could be because of stock getting split. 
<img width="858" alt="Screenshot 2020-05-09 at 8 20 08 PM" src="https://user-images.githubusercontent.com/1936503/81477058-27fb7600-9233-11ea-9eec-03df77ccafcd.png">

**Comment by bommojuvishu** [comment]
Thank you for the prompt response .I think what you said right , the stock may have splited .
I feel that data should have come like money control graph . it would be easy to analyse the stock price . But anyways thanks

**Comment by hawkeyes21** [comment]
> Thank you for the prompt response .I think what you said right , the stock may have splited . I feel that data should have come like money control graph . it would be easy to analyse the stock price . But anyways thanks

Would these random fluctuations in prices be in issue if we're training an LSTM model using this data?
