### ISSUE TITLE
Unable to fetch the data in the digitalocean

### ISSUE THREAD

**Issue by bommojuvishu** [swapniljariwala/nsepy#148]
I am trying to fetch data on the stocks in the digital ocean  .But it is not able to fetch it .it seems that server is blocking the request.
I am using the basic code . once I execute the code  it just keep on executing, no data .
My server is on bangalore location

```
from datetime import date
from nsepy import get_history
sbin = get_history(symbol='SBIN',
                   start=date(2015,1,1),
                   end=date(2015,1,10))
```

**Comment by swapniljariwala** [comment]
Please track #153
