### ISSUE TITLE
partially initialized module 'pandas' has no attribute 'plotting' (most likely due to a circular import)

### ISSUE THREAD

**Issue by ravividap** [swapniljariwala/nsepy#152]
Getting below error on importing nsepy.

Error:partially initialized module 'pandas' has no attribute 'plotting' (most likely due to a circular import)

Code Sample:
from nsepy import get_history as gh
from datetime import date

sbin = gh(symbol='SBIN', start=date(2020,6,1), end=date(2020,6,12))
print(sbin)

**Comment by BruceWayne1219** [comment]
Hey, 'sbin' in your code is a dataframe, please try sbin.head() instead
```
from nsepy import get_history as gh
from datetime import date

sbin = gh(symbol='SBIN', start=date(2020,6,1), end=date(2020,6,12))
sbin.head()
```

**Comment by ravividap** [comment]
it wasn't even reaching print statement but found that it works on my other machine. Thanks for reply
