### ISSUE TITLE
get_history infinite loading google colab

### ISSUE THREAD

**Issue by jonpsy** [swapniljariwala/nsepy#153]
Hi, 

I'm using google colab and have used %pip install nsepy, it installs fine but get_history method seems to be loading indefinetely. I've seen a thread addressing this, but this one is in google colab so i can't change something "locally". Anyone help?

**Comment by VikasSingh-DS** [comment]
Having the same problem, get_history infinite loading google colab.
from nsepy import get_history
from datetime import date
import pandas as pd

tcs = get_history(symbol="TCS", 
                    start=date(2015,1,1), 
                    end=date(2015,12,31))

**Comment by siddas27** [comment]
Same issue

**Comment by swapniljariwala** [comment]
Please run a small ping test from your local computer as well as Google collab/AWS/or any other cloud environment

> ping www1.nseindia.com

I have observed that both the IP addresses are different, which might be the problem. However I do not have a solution for it as of now.

**Comment by sanjay1122** [comment]
Thanks for great code!

How to run ping from google colab? 

Also, if DNS is different then is it possible to have fixed IP like 127.xx.xx.xx form rather than www1.nseindia.com ?

**Comment by nselearner** [comment]
Facing same issue in all cloud environment ....

Like..

Google cloud VM 
AWS
Google Colab 

Anyone please solve it

**Comment by nselearner** [comment]
Please go through this..

https://github.com/codesandbox/codesandbox-client/issues/3403

Looks similar to our problem

**Comment by nselearner** [comment]
Ping  I tried in Google cloud VM 
It's working fine ..

But when do Curl ..  access denied

**Comment by nselearner** [comment]
> Please run a small ping test from your local computer as well as Google collab/AWS/or any other cloud environment
> 
> > ping www1.nseindia.com
> 
> I have observed that both the IP addresses are different, which might be the problem. However I do not have a solution for it as of now.

Ping work fine in Google cloud VM

But when I request curl ..

It's throw access denied

**Comment by swapniljariwala** [comment]
Dear All,

Ping should work fine, but the main problem is that IP addresses are different. Can you please compare those two IPs.

Your request from cloud is not hitting the regular server, it is hitting some other server which does not return a response.

@sanjay1122 , You can run any command in notebook followed after `!`

eg. `!ping www1.nseindia.com`

Thanks
Swapnil

**Comment by sanjay1122** [comment]
Thanks Swapnil. I get following error when I run !ping in google colab. It works from my laptop.
_"/bin/bash: ping: command not found"_

I want more data from option chain, like volume, put/call contracts etc.. 
I don't see way to fetch that.

I tried to peek in code and found that all option interest data is generated from *.csv files on nseindia site and that is reason it is not available for current day. I want to get complete option chain data preferably real time. Is that possible?

Can scrapy be used?

**Comment by ElisonSherton** [comment]
Same issue @swapniljariwala . I can't run ping command from Google Colab. 

I'm interested in finding bhavcopies of options data. I saw there is a `get_price_list` for equities data, is there a similar function for derivatives data as well?

Thanks in advance.

**Comment by rjvmohite** [comment]
Is there any update for this issue? I know it says open but is there any progress that has been made or any workaround that has been found?

**Comment by abhisingh11** [comment]
Hey, even I am trying today in Google Colab and its been more than 15 mins, its still loading. Any fix  ?

**Comment by Naveen021-kgp** [comment]
@swapniljariwala  can you please provide a solution for this problem.

**Comment by uttamsingh** [comment]
@swapniljariwala i too have same problem

**Comment by jonpsy** [comment]
Closing this since no action is being taken. One may readress this in another issue.
