### ISSUE TITLE
Floating StrikePrice not supported

### ISSUE THREAD

**Issue by prakashjj** [swapniljariwala/nsepy#16]
Currently floating strike price is not supported while getting historic option prices.

Can this be fixed?

For example: IDFCBANK has got a strike price of 67.5 but I cant use it because it fails with the below error

ValueError: strike_price argument missing or not of type int

**Comment by swapniljariwala** [comment]
I've fixed it and pushed the new code,  Kindly uninstall previous version of nsepy, and install from current git branch-
`git clone https://github.com/swapniljariwala/nsepy.git`
`cd nsepy`
`python setup.py install`

Hope this solves the issue. 
Do let me know.

**Comment by prakashjj** [comment]
Thanks a lot for your quick response. It is working fine now.

Cheers
Prakash
