### ISSUE TITLE
Not Able to get History data

### ISSUE THREAD

**Issue by prakashjj** [swapniljariwala/nsepy#17]
Hi, 

I am unable to fetch any history data. No data is returned. It was working fine till last week. Are you facing similar issue?

I am trying to fetch Banknifty Option data.

**Comment by krajeevin** [comment]
Hi,

I am unable to fetch any history data based on equty . But it give index data well what i have to do.

**Comment by swapniljariwala** [comment]
nse's website may have undergone an update. I'm looking into it. It may take few days.

**Comment by swapniljariwala** [comment]
Please pull from latest master branch, Looks like issue is fixed for now.

Reason for break in functionality was probably due to update in NSE's website.

Earlier the [url for fetching historical data](https://www.nseindia.com/products/dynaContent/common/productsSymbolMapping.jsp?symbol=SBIN&segmentLink=3&symbolCount=1&series=ALL&dateRange=+&fromDate=01-05-2017&toDate=24-05-2017&dataType=PRICEVOLUME) - used to work without [any specific header fields](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields)
but now it needs **Host** and **Referer** fields in request header. This is what is included in the fix

**Comment by swapniljariwala** [comment]
# Please Note:
Take care that when you fetch data using nsepy, [save the dataframe locally on disk ](https://stackoverflow.com/questions/17098654/how-to-store-data-frame-using-pandas-python) and use the saved dataframe for iterative development
It has several benefits:

- Your code runs faster as fetching data from nse's website is time intensive
- Multiple fetches by multiple people loads NSE's servers and they may take corrective measures to limit the access by updating websites as the have done now, If we follow these basic good practices we may prevent it from happening

**Comment by prakashjj** [comment]
Hi, 

Thanks a lot for fixing that. 

On the back of your suggestion about storing the data locally, I have one question though. 

Is there a way I can use nsepy to download all the historic data in a date range without passing the expiry date.

I am mainly interested in FNO which makes it difficult as it requires the expiry date.  Please let me know if there is an easier way to download say last 6 months of FNO data without calculating the expiry date manually.

Thanks again for such a wonderful library.

**Comment by shiju-john** [comment]
Hi swapniljariwala,
Thanks for the support, It is working now ..  (y)

**Comment by swapniljariwala** [comment]
@prakashjj  I've a function which gives you expiry date which is correct in most cases, You will still have to pass year and month though, i guess it should not be a big problem to iterate over year and month.

`from nsepy.derivatives import get_expiry_date`
`expiry_date = get_expiry_date(year=2017, month=5, index=True, stock=False)`

Let me know if this works 

Just curious, what analysis do you do on option data, do you use this analysis for actual trading? Do let me know if you write blog or something about your experiments.

**Comment by prakashjj** [comment]
Hi,

Thanks for that, I will try that today evening.

I have started some studies on machine learning and trying to see if I can
some patterns in Options.

I will definitely share if something interesting I find out. Are you using
these data for any actual trading yet?

**Comment by swapniljariwala** [comment]
No, I've not used it yet.

**Comment by ApoorvV** [comment]
Great work Swapnil. I was successfully able to get historical data. However, I was unable to get real-time data during trading hours. The documentation header mentions that real-time data can be downloaded but there is no other mention of it in the documentation.
Is it possible to get real-time data. If so, please show an example code.
Apart from this, nsepy is a great module. Thanks

**Comment by anasokan** [comment]
Hi Swapnil,

I am also not getting today's data at around 5:30 PM IST 
Is there any cut-off time to get today's data as part of history.

**Comment by ashokbindra** [comment]
hi 
from yesterday i was facing same problem , i am able to get data for 31-08-22 but unable to get_history data for 1-11-22 plz help me out

**Comment by devil-dev** [comment]
I am getting empty data frames from using get history? is there a work around. Help would be greatly appreciated
