### ISSUE TITLE
can it provide per minute data

### ISSUE THREAD

**Issue by pishangujeniya** [swapniljariwala/nsepy#174]
Can it provide data per minute for any stock from NSE?

I saw the screenshots provides the data of every day.

**Comment by nishanth-** [comment]
per minute data is generally not free. Its generally a paid service from various data vendors

**Comment by pishangujeniya** [comment]
@nishanth-  

Isn't it possible to scrap, I am not asking to get live data, just historical but per minute data.

**Comment by sevakram** [comment]
Author of `jugaad-data` here, 

Minute data is not free, but you can still get tick data from NSE's website

```python

from jugaad_data.nse.live import NSELive

n = NSELive()
d = n.tick_data("HDFC")
```
`tick_data` returns tick by tick data, which is generally every second.

Caveat though, you do not get historical data, you have to download the data same day.

**Comment by sevakram** [comment]
Additionally, if you have a Zerodha account, you can still fetch minute data with [`jugaad-trader` library](https://marketsetup.in/posts/download-stock-data-zerodha/)

Hope this is useful.

**Comment by rajvardhan21** [comment]
Can we download multiple stock historical data at once and update it daily? For example,can we download all FnO stock data (mainly OHLC) and download in Excel for last one one year or so? If yes, how??
