### ISSUE TITLE
Is there a way to get list of stocks in Nifty 50 using nsepy from past?

### ISSUE THREAD

**Issue by mahi1977** [swapniljariwala/nsepy#176]
Hi, I am trying to build a database of changes in Nifty 50 stocks from the point index was created in 1996. Problem I am having is I am unable to get source of initial list of stocks in Nifty 50 when index was created, searched various sources but could not. I was wondering if there is some capability in nsepy that could help me get list of stocks in a given index in year say 2000 or 2002 or 1996. 

On the other hand, I am reverse building database based on index composition today and taking care of inclusion/exclusion past. I feel I may get result...but accuracy may be little challenged.

Any help in this regard is appreciated

**Comment by psynstein** [comment]
I have it compiled from 2008 to 2019 if you are interested

**Comment by mahi1977** [comment]
Thanks psystein, appreciate your help. Please share

**Comment by psynstein** [comment]
Please recheck the values and details. This was compiled sometime ago and
there may be errors in the entries.

**Comment by psynstein** [comment]
sorry the file didnt attach.



[Nifty50_Compiled.xlsx](https://github.com/swapniljariwala/nsepy/files/5552575/Nifty50_Compiled.xlsx)

**Comment by mahi1977** [comment]
thanks psynstein. appreciate your help
