### ISSUE TITLE
Empty dataframe is return back 

### ISSUE THREAD

**Issue by shiju-john** [swapniljariwala/nsepy#18]
getting empty data frame is return back while invoking following API from ( may 18 2017 onwards )
get_history(symbol=stockSymbol,start=fromDate,end=toDate)

**Comment by krajeevin** [comment]
same thing happen with me

**Comment by swapniljariwala** [comment]
Please track - 
https://github.com/swapniljariwala/nsepy/issues/17

**Comment by swapniljariwala** [comment]
Please refer issue https://github.com/swapniljariwala/nsepy/issues/17   for the solution
