### ISSUE TITLE
get_history of few  stocks, will not return full dataset 

### ISSUE THREAD

**Issue by shiju-john** [swapniljariwala/nsepy#20]
I am trying to download last 5 years history data (up to today). few of the stocks  are not fully downloaded , Please find the company names and its symbols 

DS Kulkarni Developers Limited	:  DSKULKARNI
Williamson Magor & Company Limited : WILLAMAGOR
Madras Fertilizers Limited: 	MADRASFERT
SPML Infra Limited	: SPMLINFRA
Visesh Infotecnics Limited :	VISESHINFO
Cinevista Limited: CINEVISTA
Soma Textiles & Industries Limited	: SOMATEX
Pritish Nandy Communications Limited	: PNC
National Steel And Agro Industries Limited : NATNLSTEEL
Infomedia Press Limited	: INFOMEDIA
Oriental Trimex Limited	: ORIENTALTL
Euro Ceramics Limited	: EUROCERA
Websol Energy System Limited	: WEBELSOLAR
Tarmat Limited	: TARMAT
Parrys Sugar Industries Limited	: PARRYSUGAR
Metkore Alloys & Industries Limited	 : METKORE
OCL Iron and Steel Limited : OISL
Kilitch Drugs (India) Limited : KILITCH
Andhra Cements Limited	 : ANDHRACEMT
Sezal Glass Limited : SEZAL

Please help to resolve the issue,

**Comment by swapniljariwala** [comment]
Hi Shiju,
Tried to pull data for DSKULKARNI and WILLAMAGOR, I couldnt see any breaks for DSKULKARNI, for WILLAMAGOR I see some breaks, can you please check on nse india's website if it gives any data or not for that period. What I suspect is, there are some stocks which dont get traded at all for some days or even weeks, for those stocks you may get such breaks. But I might be wrong, It would really help if you could check on nse's website.
DSKULKARNI 
![dsdevelopers](https://cloud.githubusercontent.com/assets/13736447/26617166/399ad4c8-45f1-11e7-8527-d9348b4f1136.png)
WILLAMAGOR
![willamagor](https://cloud.githubusercontent.com/assets/13736447/26617168/3e16c3c2-45f1-11e7-8111-065729cc8341.png)

**Comment by shiju-john** [comment]
for the  DSKULKARNI stock we didn't get the details like  close ,turnover ,volume etc.. But in NSE history the data was there. Please find the screen shot.
![screenshot from 2017-05-31 11-42-44](https://cloud.githubusercontent.com/assets/23657056/26618083/5cdf800a-45f6-11e7-8ab4-0a4066f6b855.png)

one more sample for MADRASFERT data we are getting upto  2017-04-12 , in between 2017-04-12 - 2017-05-29 data is missing , But this data is there in NSE history

**Comment by shiju-john** [comment]
Hi  swapniljariwala,
Please correct what i understood is wrong, get_history is  return back the series EQ  (Intra-day trading) only. If so, then the API is working properly 
Thanks for the support.
Shiju

**Comment by swapniljariwala** [comment]
you can try `df = get_history(symbol='MADRASFERT', start=date(2017,4,12), end=date(2017,5,29), series='BE')`

**Comment by swapniljariwala** [comment]
@shiju-john , did you try with above solution, please let me know if that works

**Comment by shiju-john** [comment]
@swapniljariwala ,
Sorry for the late replay , This is working, Thanks for the update , But i am using only EQ series ... Once again thanks for the support .

**Comment by shiju-john** [comment]
@swapniljariwala ,
Is it anyway to get the historical market depth of a stock. (In money control we will get the different  price for  bid/offer quantity in a day ). Has NSEpy had any option to get these data ?

**Comment by swapniljariwala** [comment]
you can get live market depth with get_quote function. Its just that I did not get time to document it. I'm closing this issue. Do open another issue so for market depth, so that I can track the request.
