### ISSUE TITLE
Nsepy is Not working on Cloud

### ISSUE THREAD

**Issue by manishdaga** [swapniljariwala/nsepy#220]
Hello Everyone Recently i want to build something on Stockmarket. But I cannot use nsepy on any cloud provider. I have to use google cloud or amazon AWS  both of them are not working. It is not about nsepy when I am doing wget to  nseindia.com
this is also not working on the cloud
![Screen Shot 2022-01-14 at 9 27 24 AM](https://user-images.githubusercontent.com/51750651/149449172-3bb352ba-c03b-4569-91da-451fa5d42ce5.png)
.

**Comment by vgaurav3011** [comment]
Any work around this so far? I am stuck with the same issue over both Heroku and AWS and had modeled the entire project using features from NSEpy, now not able to perform a deployment of the same.

**Comment by manishdaga** [comment]
>

**Comment by manishdaga** [comment]
@vgaurav3011  It does not work in any cloud provider

**Comment by Hanlak** [comment]
i have also had the same issue when i try run on heroku. please let this thread know if there is a workaround or altenative solution
