### ISSUE TITLE
scrape RBI Reference Rate

### ISSUE THREAD

**Issue by sharanyagantla** [swapniljariwala/nsepy#23]
How can we extract historical RBI rates from this link using nsepy.
Kindly guide me
https://www.nseindia.com/products/content/derivatives/currency/historical_rbiRate.htm

ThankYou

**Comment by swapniljariwala** [comment]
Interesting, I did not notice this earlier. I'll see if I can add support to this, this may take more time though

**Comment by swapniljariwala** [comment]
Please install from master branch, I've added the `get_rbi_ref_history` function 

```python
from datetime import date
from nsepy import get_rbi_ref_history
ref_rates = get_rbi_ref_history(date(2017,1,1), date(2017,1,30))
ref_rates.plot(y=['1 USD', '1 GBP'], secondary_y='1 GBP')
```
![ref_rates](https://user-images.githubusercontent.com/13736447/27067347-27ce77ea-5028-11e7-8393-36b7af21dcad.png)

**Comment by swapniljariwala** [comment]
It would be great if you would like to contribute, I'll try to write a guideline/documentation
