### ISSUE TITLE
Unable to get INDIAVIX data

### ISSUE THREAD

**Issue by bansalrajat82** [swapniljariwala/nsepy#27]
Df_vix = get_history(symbol="INDIAVIX", 
                    start=date(2016,1,1), 
                    end=date(2017,6,17), index=True)  

what seems wrong in this ?

**Comment by swapniljariwala** [comment]
@bansalrajat82 Fixed the issue

Reason for the issue- Bad html by nse (if you observe the source of [https://www.nseindia.com/products/dynaContent/equities/indices/hist_vix_data.jsp?&fromDate=01-Jan-2017&toDate=01-Feb-2017](https://www.nseindia.com/products/dynaContent/equities/indices/hist_vix_data.jsp?&fromDate=01-Jan-2017&toDate=01-Feb-2017)
closing <tr> tag is missing. 
Solved this by changing BeautifulSoup parser from 'html.parser' to 'lxml'

you need to ensure that lxml is installed on your system now.

**Comment by softashu** [comment]
Hi Swapnil,

can we get live VIX ie today vix?

Thannks
Ashutosh
