### ISSUE TITLE
Empty dataset while downloading sectoral indices

### ISSUE THREAD

**Issue by potholiday** [swapniljariwala/nsepy#28]
I am trying to download sectorla indexes such as nifty auto, nifty bank, nifty it etc. But the output is an empty dataframe

```
>>> from nsepy import get_history
>>> get_history(symbol="BANKAUTO",start=date(2007,1,1),end=date(2007,2,1))
Empty DataFrame
Columns: [Symbol, Series, Prev Close, Open, High, Low, Last, Close, VWAP, Volume, Turnover, Trades, Deliverable Volume, %Deliverble]
```

**Comment by potholiday** [comment]
my bad found *index=True*

**Comment by potholiday** [comment]
Sorry for closeing this issue I once more wants to reopen the same issue

NIFTYPHARMA, NIFTYENERGY, etc output empty dataset

**Comment by swapniljariwala** [comment]
Hey @potholiday , interesting username 😉 

Please try "NIFTY PHARMA" or "NIFTY ENERGY"

Its basically index name you see in drop down list on this [page](https://www.nseindia.com/products/content/equities/indices/historical_index_data.htm) in capitals.

SImilarly you can try "NIFTY QUALITY 30", "NIFTY 100" , "NIFTY50 TR 2X LEV" or even "NIFTY GS 15YRPLUS"

Hope this helps.

**Comment by potholiday** [comment]
Thank you for the quick reply and the name it just poped into my head :).  This worked
 
`get_history(symbol="NIFTY PHARMA", index=True,start=date(2007,1,1),end=date(2007,2,1))`

I thought we have remove spaces from the name.. Once more thank you :)
