### ISSUE TITLE
Is the historical data is price adjusted for bonus and stock split?

### ISSUE THREAD

**Issue by abbazs** [swapniljariwala/nsepy#31]
Swapnil,

Is the historical data is price adjusted for bonus and stock split? If not do you know how to do it? I can contribute.

Kind Regards,
Abbas

**Comment by swapniljariwala** [comment]
I would appreciate your contribution. 
NSEpy fetches prices from nse's website as it is and NSE does not seem to care about price adjustments.. Having said that if we need to adjust for bonus, stocksplit and dividends. we need to know accurately
* date of split
* ratio of split
As of now I've not come across any such page at NSE which gives this information in consistent format suitable for parsing. (Consistency of format is very crucial)
Let me know if you come across any reliable source for this info.

**Comment by abbazs** [comment]
bseindia.com provides the details at this page http://www.bseindia.com/corporates/corporate_act.aspx?expandable=3

**Comment by swapniljariwala** [comment]
we can probably write a function to fetch this data, but on how to use this information, I'll leave it to the user.

**Comment by suku-h** [comment]
I found that the ISIN code in NSE data matches the ISIN number in the link @abbazs  has provided. If scrape the words split, bonus from the list then, we should be able to fairly accurately adjust the data.

**Comment by yramamurthy** [comment]
@abbazs : did you manage to achieve this? If yes, could you give me a hint on how to adjust the OHLC for stock split/bonus please?

**Comment by abbazs** [comment]
No I didn't manage to get this done.

**Comment by suku-h** [comment]
@abbazs . Any idea how we can fetch the corporate actions from bse programmatically?

**Comment by pyrole** [comment]
I found the place on nse which stores historical corporate actions like stock splits and dividends:

https://www.nseindia.com/companytracker/cmtracker.jsp?symbol=SBIN

**Comment by shbkd** [comment]
I looked into the url and original url for data is as below:
https://www.nseindia.com/marketinfo/companyTracker/corpAction.jsp?symbol=SBIN

**Comment by pyrole** [comment]
Actually I found that nse corp action data is not present for before 2014, here is another link to fetch historical data of bonus, dividends and splits:
https://trendlyne.com/equity/Dividend/SBIN
https://trendlyne.com/equity/Split/SBIN
https://trendlyne.com/equity/Bonus/SBIN

**Comment by sumeet0077** [comment]
anyone got any working solution to fetch adjusted price ?

**Comment by writetoniloy** [comment]
# I too was looking for it. But solved it today. 
# This is done by data analytic technique and you may want to add more elements to splitFactor list though the present items should suffice most split scenario. Write back to me if you are stuck.
# Use the following code snippet to this:

import numpy as np
import pandas as pd
from nsepy import get_history
from datetime import date
import matplotlib.pyplot as plt

start_date_GOLDBEES = date(2007,3,19)

data = get_history(symbol="GOLDBEES", start=start_date_GOLDBEES, end=date.today())
data = data[~data.index.duplicated(keep='first')]
fig, ax = plt.subplots(num=None, figsize=(15, 6), dpi=80, facecolor='w', edgecolor='k')
ax.plot(data[['Close']])     # This will plot unadjusted data


def split_adjust(rPCO_uc, rPCO_lc, arg):
    splitFactor = [2//1, 3/2, 4/3, 5/2, 5/3, 3//1, 4//1, 5//1, 6//1, 7//1, 8//1, 9//1, 10//1, 100//1, 200//1]
    factor = 1.0
    newFactor = 1.0
    reverseArg = arg.copy().iloc[::-1]

    for index, row in reverseArg.iterrows():        
        rPCO = row['Prev Close'] / row['Open']
        if rPCO > rPCO_uc or rPCO < rPCO_lc:
            possibleSplitRatioIndicator = list(abs(np.array(splitFactor) - np.array([rPCO]*len(splitFactor))))
            indexOfSplitRatio = possibleSplitRatioIndicator.index(min(possibleSplitRatioIndicator))
            splitRatio = magicNo[indexOfSplitRatio]
            newFactor = factor * splitRatio
            if (index != start_date_GOLDBEES): 
                print ('Possible Split on', index, 'with split ratio=', splitRatio)
            reverseArg.loc[index, 'Prev Close']         /= splitRatio
    
        if (factor != 1): 
            reverseArg.loc[index, 'Prev Close']        = round(reverseArg.loc[index, 'Prev Close'] / factor, 2)
            reverseArg.loc[index, 'Open']              = round(reverseArg.loc[index, 'Open'] / factor, 2)
            reverseArg.loc[index, 'High']              = round(reverseArg.loc[index, 'High'] / factor, 2)
            reverseArg.loc[index, 'Low']               = round(reverseArg.loc[index, 'Low'] / factor, 2)
            reverseArg.loc[index, 'Last']              = round(reverseArg.loc[index, 'Last'] / factor, 2)
            reverseArg.loc[index, 'Close']             = round(reverseArg.loc[index, 'Close'] / factor, 2)
            reverseArg.loc[index, 'VWAP']              = round(reverseArg.loc[index, 'VWAP'] / factor, 2)
            reverseArg.loc[index, 'Volume']            = round(reverseArg.loc[index, 'Volume'] * factor, 2)
            reverseArg.loc[index, 'Deliverable Volume']=round(reverseArg.loc[index,'Deliverable Volume']*factor,2)
        factor = newFactor

    return reverseArg.iloc[::-1]


arg = data.iloc[:,:]#.copy()
print()
split_adjust_data = split_adjust(1.35, 0.65, arg)
print()
#print(split_adjust_data.iloc[:,:8])
fig, ax = plt.subplots(num=None, figsize=(15, 6), dpi=80, facecolor='w', edgecolor='k')
ax.plot(split_adjust_data[['Close']])    # This will plot Split or Bonus adjusted data
