### ISSUE TITLE
get_price_list not working

### ISSUE THREAD

**Issue by vivkshrma0** [swapniljariwala/nsepy#36]
AttributeError: module 'nsepy' has no attribute 'get_price_list'

**Comment by swapniljariwala** [comment]
@vivkshrma0, I guess I missed one line in documentation. I'll add it soon, thanks
This should work now

```Python
from nsepy.history import get_price_list
prices = get_price_list(dt=date(2015,1,1))
```

**Comment by vivkshrma0** [comment]
Thanks ,its working :)
