### ISSUE TITLE
Empty Data Frame returned 

### ISSUE THREAD

**Issue by arunsivaraj** [swapniljariwala/nsepy#48]
I was able to see results till yesterday for **get_history** function, but today (24/01/2018, 9.30 PM IST) i am getting empty data frame like below.
**Columns: [Symbol, Series, Prev Close, Open, High, Low, Last, Close, VWAP, Volume, Turnover, Trades, Deliverable Volume, %Deliverble]**

I have tried uninstalling, reinstalled and upgraded nsepy, but still no luck.

**Comment by prakashjj** [comment]
Hi...not sure if it's a problem with code itself or with nSE servers. Have been facing this issue quite frequently for last few days.

**Comment by arunsivaraj** [comment]
Now the datas are retrieving properly and able to achieve the result. Not sure what is happening in the backend.
