### ISSUE TITLE
ImportError: cannot import name 'get_history'

### ISSUE THREAD

**Issue by sashwath91** [swapniljariwala/nsepy#55]
I keep getting below error on running. I recently installed nsepy.

ImportError: cannot import name 'get_history'

code is very basic:

from datetime import date
from nsepy import get_history
sbin = nsepy.get_history(symbol='SBIN', start=date(2015,1,1), end=date(2015,1,10))

**Comment by sjerry4u** [comment]
Should be `import nsepy` to do `nsepy.get_history` or ` from nsepy import get_history` then use `get_history`
