### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by csayantan** [swapniljariwala/nsepy#6]
> ConnectionError: HTTPConnectionPool(host='www.nseindia.com', port=80): Max retries exceeded with url: /products/dynaContent/common/productsSymbolMapping.jsp?symbol=SBIN&segmentLink=3&symbolCount=%201&series=EQ&dateRange=+%20%20%20%20%20%20%20%20%20%20%20%20&fromDate=17-07-2011&toDate=16-10-2011&dataType=PRICEVOLUMEDELIVERABLE (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f50c81f1d90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

`

> Code:

from nsepy.archives import get_price_history
from datetime import date
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

df = get_price_history(stock = 'SBIN', start = date(2016,01,01), end = date(2016,01,20))
## sns.set()
# sns.pairplot(df)
## sns.plt.show()

sns.set_style("whitegrid")

plt.plot(df['Close'],df['Volume'])
sns.plt.show()

`

**Comment by swapniljariwala** [comment]
Did it suddenly stop working? If yes then probably its not NSEpy's fault. Your IP might have got blocked by NSE's website

**Comment by csayantan** [comment]
yup. any checker / exception handling can you suggest ?

**Comment by swapniljariwala** [comment]
You can except on ConnectionError but that wont solve our problem. Can do much if server is refusing.

**Comment by swapniljariwala** [comment]
Hope this is resolved.

**Comment by ankitprinceishan** [comment]
nope after sometimes it shows the same
