### ISSUE TITLE
Interday 1min Data

### ISSUE THREAD

**Issue by csayantan** [swapniljariwala/nsepy#9]
Hi

Any chance of having Interday 1min Data or historic tick data for generating strategies and backtesting for inter day in future on EOD basis at-least in future?

**Comment by csayantan** [comment]
is there any future plan for it or it is out of the scope of this utility ?

**Comment by swapniljariwala** [comment]
minute level data- I'm not sure if that is available on NSE publicly.

I'm going to write a backtesting framework or use zipline with nsepy (depending on how i get time)

**Comment by csayantan** [comment]
have u added backtesting framework in this in current version?

**Comment by swapniljariwala** [comment]
sorry, not yet. back testing is outside nsepy scope, I'll create another repository for backtesting with zipline or otherwise.

**Comment by swapniljariwala** [comment]
Regarding minute data, unfortunately minute data is not available for free on internet. There are several vendors but I haven't taken any subscription yet.
